/** Synthetic demonstration data only. No row describes a real user or event. */

const category = (id, name, world, rounds, installations, replayRate, reports, color) => ({
  id,
  name,
  world,
  rounds,
  installations,
  replayRate,
  reports,
  color,
});

export const DEMO_SCENARIOS = Object.freeze({
  healthy: {
    id: 'healthy',
    name: 'Healthy growth',
    note: 'Synthetic scale-ready cohort',
    asOf: '2026-08-20T06:00:00+02:00',
    play: {
      downloads: 268,
      activeInstallBase: 224,
      storeVisitors: 1084,
      storeAcquisitions: 268,
      storeConversion: 0.247,
      crashFree: 0.998,
      anrRate: 0.0012,
    },
    activatedInstallations: 203,
    webCompletedInstallations: 42,
    completedRounds: 1194,
    differentDayReplay: 58,
    shares: 41,
    referredActivations: 25,
    totalReports: 21,
    seriousReports: 2,
    funnel: {
      firstOpen: 221,
      roundStart: 1280,
      revealComplete: 1162,
      firstRoundComplete: 167,
      secondRound: 91,
    },
    trend: [9, 11, 12, 10, 13, 14, 16, 15, 18, 20, 19, 23, 25, 22, 27, 29, 30, 28, 33, 35, 37, 41, 39, 44, 46, 49, 47, 53, 55, 59],
    categories: [
      category('sport-football', 'Football', 'Sport', 186, 92, 0.31, 1, '#D8FF4F'),
      category('gaming-minecraft', 'Minecraft', 'Gaming', 151, 71, 0.28, 0, '#AF8CFF'),
      category('tabletop-dungeons-dragons', 'Dungeons & Dragons', 'Tabletop', 137, 59, 0.39, 2, '#FF725E'),
      category('sport-padel', 'Padel', 'Sport', 124, 63, 0.24, 1, '#72A7FF'),
      category('food-cocktails', 'Cocktails', 'Food & drink', 96, 51, 0.22, 0, '#FFC65A'),
      category('music-music-production', 'Music production', 'Music', 82, 39, 0.33, 1, '#75E6C3'),
      category('studies-medicine', 'Medicine', 'Studies', 75, 34, 0.29, 3, '#FF84C6'),
      category('creative-pottery', 'Pottery', 'Creative', 68, 31, 0.26, 0, '#63E6FF'),
    ],
    mixes: [
      { name: 'Football + Padel', worlds: ['Sport'], rounds: 88, color: '#D8FF4F' },
      { name: 'D&D + Minecraft', worlds: ['Tabletop', 'Gaming'], rounds: 74, color: '#AF8CFF' },
      { name: 'Cocktails + Wine', worlds: ['Food & drink'], rounds: 57, color: '#FFC65A' },
      { name: 'Medicine + Psychology', worlds: ['Studies'], rounds: 46, color: '#FF84C6' },
      { name: 'Pottery + Woodworking', worlds: ['Creative'], rounds: 39, color: '#63E6FF' },
    ],
    requests: [
      { label: 'Floorball tactics', count: 18, status: 'Approved', trend: '+7', age: '6h' },
      { label: 'Swiss railways', count: 13, status: 'Review', trend: '+4', age: '11h' },
      { label: 'Emergency medicine', count: 11, status: 'Generating', trend: '+6', age: '2h' },
      { label: 'K-pop choreography', count: 9, status: 'Review', trend: '+3', age: '1d' },
      { label: 'Watchmaking', count: 7, status: 'Ready', trend: '+2', age: '1d' },
    ],
    campaigns: [
      { code: 'organic_share', label: 'In-game shares', source: 'Owned', spend: 0, activations: 58, rounds: 344, referredActivations: 19 },
      { code: 'reddit_tabletop', label: 'Tabletop communities', source: 'Organic', spend: 0, activations: 31, rounds: 198, referredActivations: 8 },
      { code: 'uni_clubs_bern', label: 'University clubs', source: 'Outreach', spend: 0, activations: 24, rounds: 126, referredActivations: 7 },
      { code: 'creator_padel01', label: 'Padel creator pilot', source: 'Creator', spend: 30, activations: 17, rounds: 104, referredActivations: 5 },
    ],
  },
  launch: {
    id: 'launch',
    name: 'Launch week',
    note: 'Synthetic early baseline',
    asOf: '2026-08-20T06:00:00+02:00',
    play: {
      downloads: 64,
      activeInstallBase: 57,
      storeVisitors: 281,
      storeAcquisitions: 64,
      storeConversion: 0.228,
      crashFree: 0.997,
      anrRate: 0.0019,
    },
    activatedInstallations: 49,
    webCompletedInstallations: 12,
    completedRounds: 238,
    differentDayReplay: 7,
    shares: 5,
    referredActivations: 3,
    totalReports: 4,
    seriousReports: 0,
    funnel: {
      firstOpen: 56,
      roundStart: 260,
      revealComplete: 228,
      firstRoundComplete: 38,
      secondRound: 15,
    },
    trend: [2, 4, 3, 7, 8, 11, 14],
    categories: [
      category('sport-football', 'Football', 'Sport', 45, 24, 0.21, 0, '#D8FF4F'),
      category('gaming-minecraft', 'Minecraft', 'Gaming', 39, 18, 0.18, 0, '#AF8CFF'),
      category('sport-padel', 'Padel', 'Sport', 31, 17, 0.19, 1, '#72A7FF'),
      category('food-cocktails', 'Cocktails', 'Food & drink', 27, 15, 0.2, 0, '#FFC65A'),
      category('tabletop-dungeons-dragons', 'Dungeons & Dragons', 'Tabletop', 22, 12, 0.25, 1, '#FF725E'),
    ],
    mixes: [
      { name: 'Football + Padel', worlds: ['Sport'], rounds: 19, color: '#D8FF4F' },
      { name: 'D&D + Minecraft', worlds: ['Tabletop', 'Gaming'], rounds: 14, color: '#AF8CFF' },
      { name: 'Cocktails + Wine', worlds: ['Food & drink'], rounds: 9, color: '#FFC65A' },
    ],
    requests: [
      { label: 'Floorball tactics', count: 6, status: 'Review', trend: '+3', age: '4h' },
      { label: 'Emergency medicine', count: 4, status: 'Review', trend: '+2', age: '9h' },
      { label: 'K-pop choreography', count: 3, status: 'Review', trend: '+1', age: '1d' },
    ],
    campaigns: [
      { code: 'tester_group', label: 'Closed-test group', source: 'Owned', spend: 0, activations: 28, rounds: 143, referredActivations: 2 },
      { code: 'organic_share', label: 'In-game shares', source: 'Owned', spend: 0, activations: 9, rounds: 41, referredActivations: 1 },
    ],
  },
  attention: {
    id: 'attention',
    name: 'Needs attention',
    note: 'Synthetic quality-alert cohort',
    asOf: '2026-08-20T06:00:00+02:00',
    play: {
      downloads: 192,
      activeInstallBase: 119,
      storeVisitors: 691,
      storeAcquisitions: 192,
      storeConversion: 0.278,
      crashFree: 0.987,
      anrRate: 0.0061,
    },
    activatedInstallations: 126,
    webCompletedInstallations: 19,
    completedRounds: 402,
    differentDayReplay: 13,
    shares: 8,
    referredActivations: 4,
    totalReports: 28,
    seriousReports: 5,
    funnel: {
      firstOpen: 168,
      roundStart: 487,
      revealComplete: 356,
      firstRoundComplete: 84,
      secondRound: 24,
    },
    trend: [24, 23, 27, 25, 20, 21, 18, 19, 17, 16, 14, 13, 12, 13, 10, 11, 9, 8, 10, 7, 8, 6, 7, 5, 6, 5, 4, 5, 4, 3],
    categories: [
      category('gaming-minecraft', 'Minecraft', 'Gaming', 82, 41, 0.12, 2, '#AF8CFF'),
      category('sport-football', 'Football', 'Sport', 67, 39, 0.11, 1, '#D8FF4F'),
      category('community-anime-lore', 'Anime lore', 'Community', 59, 31, 0.09, 9, '#FF725E'),
      category('food-cocktails', 'Cocktails', 'Food & drink', 43, 28, 0.08, 2, '#FFC65A'),
      category('studies-medicine', 'Medicine', 'Studies', 37, 21, 0.1, 7, '#FF84C6'),
    ],
    mixes: [
      { name: 'Minecraft + Anime lore', worlds: ['Gaming', 'Community'], rounds: 32, color: '#AF8CFF' },
      { name: 'Football + Cocktails', worlds: ['Sport', 'Food & drink'], rounds: 18, color: '#FFC65A' },
      { name: 'Medicine + Biology', worlds: ['Studies'], rounds: 12, color: '#FF84C6' },
    ],
    requests: [
      { label: 'Formula Student', count: 21, status: 'Review', trend: '+11', age: '3h' },
      { label: 'Watchmaking', count: 19, status: 'Review', trend: '+8', age: '5h' },
      { label: 'Swiss politics', count: 15, status: 'Sensitive', trend: '+6', age: '8h' },
      { label: 'Emergency medicine', count: 12, status: 'Blocked', trend: '+5', age: '1d' },
    ],
    campaigns: [
      { code: 'creator_general01', label: 'General creator pilot', source: 'Creator', spend: 60, activations: 8, rounds: 18, referredActivations: 0 },
      { code: 'organic_share', label: 'In-game shares', source: 'Owned', spend: 0, activations: 12, rounds: 36, referredActivations: 3 },
      { code: 'broad_social', label: 'Broad social post', source: 'Organic', spend: 0, activations: 7, rounds: 14, referredActivations: 1 },
    ],
  },
});

export function cloneScenario(id = 'healthy') {
  return structuredClone(DEMO_SCENARIOS[id] ?? DEMO_SCENARIOS.healthy);
}
